### ISSUE TITLE
Blurry, low quality background image

### ISSUE THREAD

**Issue by Kuboczoch** [eudoxia0/eudoxia0.github.io#15]
After 0.5s your background is changing to that:

![image](https://user-images.githubusercontent.com/20823919/91855000-d7d27480-ec64-11ea-9860-24b7b859fba7.png)

Google Chrome Version 85.0.4183.83

**Comment by eudoxia0** [comment]
Thank you for pointing this out, and sorry for the delay in acknowledging! This is fixed by #16.
