### ISSUE TITLE
css - 100vw causing horizontal overflow, but only if more than one.

### ISSUE THREAD

**Issue by vagreargnatry** [eudoxia0/eudoxia0.github.io#24]
Hello, could you please change your css to hide the overflowing horizontal scrollbar?

https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one

I think it would be good to delete these two lines of `max-width: 100vw` and (optionally) add `max-width: 100%` to the html element.

https://github.com/eudoxia0/eudoxia0.github.io/blob/2a60d8a95ca9dd4f28612c9e134a7a64d7021a01/assets/main.scss#L111
https://github.com/eudoxia0/eudoxia0.github.io/blob/2a60d8a95ca9dd4f28612c9e134a7a64d7021a01/assets/main.scss#L106

before:
![before](https://user-images.githubusercontent.com/104709852/210158362-6f22d93a-6fbc-4bd4-b031-0e5fbda5fa7d.png)
after:
![after](https://user-images.githubusercontent.com/104709852/210158364-fb1b280f-9a14-442a-94b7-0ed8729da451.png)

**Comment by eudoxia0** [comment]
Huh that's interesting. I hadn't noticed that.

**Comment by eudoxia0** [comment]
I don't see horizontal overflow at any zoom level. Would you mind sharing your device sizes?

**Comment by eudoxia0** [comment]
Ok I made the changes here: 

https://github.com/eudoxia0/eudoxia0.github.io/commit/7419fa67ab9144edb11b824323426da5733c7b7e

https://github.com/eudoxia0/eudoxia0.github.io/commit/dfacbbfe2dc78f5f90bf265459971626c298756c

After confirming that it doesn't break anything. Does this work on your end?

**Comment by vagreargnatry** [comment]
Thanks! It works now. My laptop's resolution is 1920x1080 and it has a system scale as 125%.

**Comment by eudoxia0** [comment]
Thanks for reporting!
