### ISSUE TITLE
Linear Types and Exceptions. Question

### ISSUE THREAD

**Issue by JohnGurin** [eudoxia0/eudoxia0.github.io#45]
```rust
void h(string* ptr) {
  let z = allocate(1234);
  if (randBool()) {
    _free_intptr(z);
    _free_str(ptr);
    throw "Halt";
  }
  _free_intptr(z);
  _free_str(ptr); // isn't this line redundant?
}
```
https://github.com/eudoxia0/eudoxia0.github.io/blob/master/article/_posts/2021-08-07-linear-types-exceptions.md?plain=1#L652

**Comment by eudoxia0** [comment]
How so?

It's deallocating on the exception-free case.

**Comment by JohnGurin** [comment]
Apparently, I misunderstood the example and thought the functions were independent. Maybe the `ptr` could be named `x_ptr`.
