### ISSUE TITLE
NaNs in graphs for "State of the Common Lisp Ecosystem"

### ISSUE THREAD

**Issue by Archenoth** [eudoxia0/eudoxia0.github.io#7]
In the last section of [growth](http://eudoxia.me/article/common-lisp-sotu-2015/#growth), I see:

![NaNNaNNaNNaNNaNNaNNaNNaN Batman!](https://cloud.githubusercontent.com/assets/1385527/11928383/66f2be46-a790-11e5-8c77-8f03c6cc3b9b.png)

Something tells me this isn't quite what you were going for.

This looks like an issue in sotu.js [here](https://github.com/eudoxia0/eudoxia0.github.io/blob/master/assets/js/sotu.js#L59)...

This is on Firefox 43.0 on Linux Mint 17.2 Rafaela.

**Comment by eudoxia0** [comment]
Fixed by making them images
