### ISSUE TITLE
Mastodon and Matrix

### ISSUE THREAD

**Issue by Hexstream** [eudoxia0/eudoxia0.github.io#70]
Hello,

[Your latest article](https://borretti.me/article/client-freedom) complains a lot about Twitter, it seems to me [Mastodon](https://en.wikipedia.org/wiki/Mastodon_(social_network)) rather thoroughly addresses your concerns.

In the same vein, you may like to look into [Matrix](https://en.wikipedia.org/wiki/Matrix_(protocol)) as an alternative to Discord, although I am not familiar enough with it to confirm that it is competitive with Discord in terms of usability and features.

**Comment by eudoxia0** [comment]
I don't like Mastodon for orthogonal reasons, but I've been meaning to look into Matrix.

**Comment by Hexstream** [comment]
If I may ask, "_orthogonal reasons_"??
